from BaseClasses import Location


class SpiritValleyLocation(Location):
    game = "Spirit Valley"


spirit_id_start = 0
spirit_locations = {
    "Obtain a Pusseen Spirit": spirit_id_start + 1,
    "Obtain a Boobae Spirit": spirit_id_start + 2,
    "Obtain a Octopussy Spirit": spirit_id_start + 3,
    "Obtain a Petunia Spirit": spirit_id_start + 4,
    "Obtain a Beebee Spirit": spirit_id_start + 5,
    "Obtain a Slimee Spirit": spirit_id_start + 6,
    "Obtain a Wolfy Spirit": spirit_id_start + 7,
    "Obtain a Ursie Spirit": spirit_id_start + 8,
    "Obtain a Gloria Spirit": spirit_id_start + 9,
    "Obtain a Serpentina Spirit": spirit_id_start + 10,
    "Obtain a Belle Spirit": spirit_id_start + 11,
    "Obtain a Oakie Spirit": spirit_id_start + 12,
    "Obtain a Trissy Spirit": spirit_id_start + 13,
    "Obtain a Spinnie Spirit": spirit_id_start + 14,
    "Obtain a Chubbie Spirit": spirit_id_start + 15,
    "Obtain a Bunni Spirit": spirit_id_start + 16,
    "Obtain a Tinky Spirit": spirit_id_start + 17,
    "Obtain a Rawry Spirit": spirit_id_start + 18,
    "Obtain a Serpentax Spirit": spirit_id_start + 19,
    "Obtain a Birdy Spirit": spirit_id_start + 20,
    "Obtain a Cactee Spirit": spirit_id_start + 21,
    "Obtain a Twerky Spirit": spirit_id_start + 22,
    "Obtain a Bovina Spirit": spirit_id_start + 23,
    "Obtain a Lacteena Spirit": spirit_id_start + 24,
    "Obtain a Hornie Spirit": spirit_id_start + 25,
    "Obtain a Buzzeena Spirit": spirit_id_start + 26,
    "Obtain a Triboobe Spirit": spirit_id_start + 27,
    "Obtain a Flora Spirit": spirit_id_start + 28,
    "Obtain a Growleen Spirit": spirit_id_start + 29,
    "Obtain a Gloreen Spirit": spirit_id_start + 30,
    "Obtain a Bellend Spirit": spirit_id_start + 31,
    "Obtain a Kittypus Spirit": spirit_id_start + 32,
    "Obtain a Dripsy Spirit": spirit_id_start + 33,
    "Obtain a Octocunt Spirit": spirit_id_start + 34,
    "Obtain a Harlie Spirit": spirit_id_start + 35,
    "Obtain a Domina Spirit": spirit_id_start + 36,
    "Obtain a Dracoomer Spirit": spirit_id_start + 37,
    "Obtain a Bearboo Spirit": spirit_id_start + 38,
    "Obtain a Megaboob Spirit": spirit_id_start + 39,
    "Obtain a Thiccsie Spirit": spirit_id_start + 40,
    "Obtain a Sexybun Spirit": spirit_id_start + 41,
    "Obtain a Mamaoak Spirit": spirit_id_start + 42,
    "Obtain a Pinchie Spirit": spirit_id_start + 43,
    "Obtain a Marinel Spirit": spirit_id_start + 44,
    "Obtain a Udderella Spirit": spirit_id_start + 45,
    "Obtain a Sharky Spirit": spirit_id_start + 46,
    "Obtain a Faerie Spirit": spirit_id_start + 47,
    "Obtain a Twerqueen Spirit": spirit_id_start + 48,
    "Obtain a Chocostar Spirit": spirit_id_start + 49,
    "Obtain a Amazona Spirit": spirit_id_start + 50,
    "Obtain a Jellygal Spirit": spirit_id_start + 51,
    "Obtain a Harpie Spirit": spirit_id_start + 52,
    "Obtain a Arachna Spirit": spirit_id_start + 53,
    "Obtain a Succubae Spirit": spirit_id_start + 54,
    "Obtain a Panthera Spirit": spirit_id_start + 55,
    "Obtain a Boobarella Spirit": spirit_id_start + 56,
    "Obtain a Octomommy Spirit": spirit_id_start + 57,
    "Obtain a Queenbee Spirit": spirit_id_start + 58,
    "Obtain a Gangfang Spirit": spirit_id_start + 59,
    "Obtain a Jawsy Spirit": spirit_id_start + 60,
    "Obtain a Polaria Spirit": spirit_id_start + 61,
    "Obtain a Slithereen Spirit": spirit_id_start + 62,
    "Obtain a Jellybish Spirit": spirit_id_start + 63,
    "Obtain a Valkyrie Spirit": spirit_id_start + 64,
    "Obtain a Slushie Spirit": spirit_id_start + 65,
    "Obtain a Deardeer Spirit": spirit_id_start + 66,
    "Obtain a Snowbae Spirit": spirit_id_start + 67,
    "Obtain a Unihorn Spirit": spirit_id_start + 68,
    "Obtain a Fungie Spirit": spirit_id_start + 69,
    "Obtain a Lizzie Spirit": spirit_id_start + 70,
    "Obtain a Juggsie Spirit": spirit_id_start + 71,
    "Obtain a Dominatrix Spirit": spirit_id_start + 72,
    "Obtain a Seraphina Spirit": spirit_id_start + 73,
    "Obtain a Centiboob Spirit": spirit_id_start + 74,
    "Obtain a EV-3 Spirit": spirit_id_start + 75,
}

spirit_affection_id_start = spirit_id_start + 75
spirit_affection_locations = {
    "Get Pusseen to Affection LV1": spirit_affection_id_start + 1,
    "Get Pusseen to Affection LV2": spirit_affection_id_start + 2,
    "Get Pusseen to Affection LV3": spirit_affection_id_start + 3,
    "Get Pusseen to Affection LV4": spirit_affection_id_start + 4,
    "Get Pusseen to Affection LV5": spirit_affection_id_start + 5,
    "Get Boobae to Affection LV1": spirit_affection_id_start + 6,
    "Get Boobae to Affection LV2": spirit_affection_id_start + 7,
    "Get Boobae to Affection LV3": spirit_affection_id_start + 8,
    "Get Boobae to Affection LV4": spirit_affection_id_start + 9,
    "Get Boobae to Affection LV5": spirit_affection_id_start + 10,
    "Get Octopussy to Affection LV1": spirit_affection_id_start + 11,
    "Get Octopussy to Affection LV2": spirit_affection_id_start + 12,
    "Get Octopussy to Affection LV3": spirit_affection_id_start + 13,
    "Get Octopussy to Affection LV4": spirit_affection_id_start + 14,
    "Get Octopussy to Affection LV5": spirit_affection_id_start + 15,
    "Get Petunia to Affection LV1": spirit_affection_id_start + 16,
    "Get Petunia to Affection LV2": spirit_affection_id_start + 17,
    "Get Petunia to Affection LV3": spirit_affection_id_start + 18,
    "Get Petunia to Affection LV4": spirit_affection_id_start + 19,
    "Get Petunia to Affection LV5": spirit_affection_id_start + 20,
    "Get Beebee to Affection LV1": spirit_affection_id_start + 21,
    "Get Beebee to Affection LV2": spirit_affection_id_start + 22,
    "Get Beebee to Affection LV3": spirit_affection_id_start + 23,
    "Get Beebee to Affection LV4": spirit_affection_id_start + 24,
    "Get Beebee to Affection LV5": spirit_affection_id_start + 25,
    "Get Slimee to Affection LV1": spirit_affection_id_start + 26,
    "Get Slimee to Affection LV2": spirit_affection_id_start + 27,
    "Get Slimee to Affection LV3": spirit_affection_id_start + 28,
    "Get Slimee to Affection LV4": spirit_affection_id_start + 29,
    "Get Slimee to Affection LV5": spirit_affection_id_start + 30,
    "Get Wolfy to Affection LV1": spirit_affection_id_start + 31,
    "Get Wolfy to Affection LV2": spirit_affection_id_start + 32,
    "Get Wolfy to Affection LV3": spirit_affection_id_start + 33,
    "Get Wolfy to Affection LV4": spirit_affection_id_start + 34,
    "Get Wolfy to Affection LV5": spirit_affection_id_start + 35,
    "Get Ursie to Affection LV1": spirit_affection_id_start + 36,
    "Get Ursie to Affection LV2": spirit_affection_id_start + 37,
    "Get Ursie to Affection LV3": spirit_affection_id_start + 38,
    "Get Ursie to Affection LV4": spirit_affection_id_start + 39,
    "Get Ursie to Affection LV5": spirit_affection_id_start + 40,
    "Get Gloria to Affection LV1": spirit_affection_id_start + 41,
    "Get Gloria to Affection LV2": spirit_affection_id_start + 42,
    "Get Gloria to Affection LV3": spirit_affection_id_start + 43,
    "Get Gloria to Affection LV4": spirit_affection_id_start + 44,
    "Get Gloria to Affection LV5": spirit_affection_id_start + 45,
    "Get Serpentina to Affection LV1": spirit_affection_id_start + 46,
    "Get Serpentina to Affection LV2": spirit_affection_id_start + 47,
    "Get Serpentina to Affection LV3": spirit_affection_id_start + 48,
    "Get Serpentina to Affection LV4": spirit_affection_id_start + 49,
    "Get Serpentina to Affection LV5": spirit_affection_id_start + 50,
    "Get Belle to Affection LV1": spirit_affection_id_start + 51,
    "Get Belle to Affection LV2": spirit_affection_id_start + 52,
    "Get Belle to Affection LV3": spirit_affection_id_start + 53,
    "Get Belle to Affection LV4": spirit_affection_id_start + 54,
    "Get Belle to Affection LV5": spirit_affection_id_start + 55,
    "Get Oakie to Affection LV1": spirit_affection_id_start + 56,
    "Get Oakie to Affection LV2": spirit_affection_id_start + 57,
    "Get Oakie to Affection LV3": spirit_affection_id_start + 58,
    "Get Oakie to Affection LV4": spirit_affection_id_start + 59,
    "Get Oakie to Affection LV5": spirit_affection_id_start + 60,
    "Get Trissy to Affection LV1": spirit_affection_id_start + 61,
    "Get Trissy to Affection LV2": spirit_affection_id_start + 62,
    "Get Trissy to Affection LV3": spirit_affection_id_start + 63,
    "Get Trissy to Affection LV4": spirit_affection_id_start + 64,
    "Get Trissy to Affection LV5": spirit_affection_id_start + 65,
    "Get Spinnie to Affection LV1": spirit_affection_id_start + 66,
    "Get Spinnie to Affection LV2": spirit_affection_id_start + 67,
    "Get Spinnie to Affection LV3": spirit_affection_id_start + 68,
    "Get Spinnie to Affection LV4": spirit_affection_id_start + 69,
    "Get Spinnie to Affection LV5": spirit_affection_id_start + 70,
    "Get Chubbie to Affection LV1": spirit_affection_id_start + 71,
    "Get Chubbie to Affection LV2": spirit_affection_id_start + 72,
    "Get Chubbie to Affection LV3": spirit_affection_id_start + 73,
    "Get Chubbie to Affection LV4": spirit_affection_id_start + 74,
    "Get Chubbie to Affection LV5": spirit_affection_id_start + 75,
    "Get Bunni to Affection LV1": spirit_affection_id_start + 76,
    "Get Bunni to Affection LV2": spirit_affection_id_start + 77,
    "Get Bunni to Affection LV3": spirit_affection_id_start + 78,
    "Get Bunni to Affection LV4": spirit_affection_id_start + 79,
    "Get Bunni to Affection LV5": spirit_affection_id_start + 80,
    "Get Tinky to Affection LV1": spirit_affection_id_start + 81,
    "Get Tinky to Affection LV2": spirit_affection_id_start + 82,
    "Get Tinky to Affection LV3": spirit_affection_id_start + 83,
    "Get Tinky to Affection LV4": spirit_affection_id_start + 84,
    "Get Tinky to Affection LV5": spirit_affection_id_start + 85,
    "Get Rawry to Affection LV1": spirit_affection_id_start + 86,
    "Get Rawry to Affection LV2": spirit_affection_id_start + 87,
    "Get Rawry to Affection LV3": spirit_affection_id_start + 88,
    "Get Rawry to Affection LV4": spirit_affection_id_start + 89,
    "Get Rawry to Affection LV5": spirit_affection_id_start + 90,
    "Get Serpentax to Affection LV1": spirit_affection_id_start + 91,
    "Get Serpentax to Affection LV2": spirit_affection_id_start + 92,
    "Get Serpentax to Affection LV3": spirit_affection_id_start + 93,
    "Get Serpentax to Affection LV4": spirit_affection_id_start + 94,
    "Get Serpentax to Affection LV5": spirit_affection_id_start + 95,
    "Get Birdy to Affection LV1": spirit_affection_id_start + 96,
    "Get Birdy to Affection LV2": spirit_affection_id_start + 97,
    "Get Birdy to Affection LV3": spirit_affection_id_start + 98,
    "Get Birdy to Affection LV4": spirit_affection_id_start + 99,
    "Get Birdy to Affection LV5": spirit_affection_id_start + 100,
    "Get Cactee to Affection LV1": spirit_affection_id_start + 101,
    "Get Cactee to Affection LV2": spirit_affection_id_start + 102,
    "Get Cactee to Affection LV3": spirit_affection_id_start + 103,
    "Get Cactee to Affection LV4": spirit_affection_id_start + 104,
    "Get Cactee to Affection LV5": spirit_affection_id_start + 105,
    "Get Twerky to Affection LV1": spirit_affection_id_start + 106,
    "Get Twerky to Affection LV2": spirit_affection_id_start + 107,
    "Get Twerky to Affection LV3": spirit_affection_id_start + 108,
    "Get Twerky to Affection LV4": spirit_affection_id_start + 109,
    "Get Twerky to Affection LV5": spirit_affection_id_start + 110,
    "Get Bovina to Affection LV1": spirit_affection_id_start + 111,
    "Get Bovina to Affection LV2": spirit_affection_id_start + 112,
    "Get Bovina to Affection LV3": spirit_affection_id_start + 113,
    "Get Bovina to Affection LV4": spirit_affection_id_start + 114,
    "Get Bovina to Affection LV5": spirit_affection_id_start + 115,
    "Get Lacteena to Affection LV1": spirit_affection_id_start + 116,
    "Get Lacteena to Affection LV2": spirit_affection_id_start + 117,
    "Get Lacteena to Affection LV3": spirit_affection_id_start + 118,
    "Get Lacteena to Affection LV4": spirit_affection_id_start + 119,
    "Get Lacteena to Affection LV5": spirit_affection_id_start + 120,
    "Get Hornie to Affection LV1": spirit_affection_id_start + 121,
    "Get Hornie to Affection LV2": spirit_affection_id_start + 122,
    "Get Hornie to Affection LV3": spirit_affection_id_start + 123,
    "Get Hornie to Affection LV4": spirit_affection_id_start + 124,
    "Get Hornie to Affection LV5": spirit_affection_id_start + 125,
    "Get Buzzeena to Affection LV1": spirit_affection_id_start + 126,
    "Get Buzzeena to Affection LV2": spirit_affection_id_start + 127,
    "Get Buzzeena to Affection LV3": spirit_affection_id_start + 128,
    "Get Buzzeena to Affection LV4": spirit_affection_id_start + 129,
    "Get Buzzeena to Affection LV5": spirit_affection_id_start + 130,
    "Get Triboobe to Affection LV1": spirit_affection_id_start + 131,
    "Get Triboobe to Affection LV2": spirit_affection_id_start + 132,
    "Get Triboobe to Affection LV3": spirit_affection_id_start + 133,
    "Get Triboobe to Affection LV4": spirit_affection_id_start + 134,
    "Get Triboobe to Affection LV5": spirit_affection_id_start + 135,
    "Get Flora to Affection LV1": spirit_affection_id_start + 136,
    "Get Flora to Affection LV2": spirit_affection_id_start + 137,
    "Get Flora to Affection LV3": spirit_affection_id_start + 138,
    "Get Flora to Affection LV4": spirit_affection_id_start + 139,
    "Get Flora to Affection LV5": spirit_affection_id_start + 140,
    "Get Growleen to Affection LV1": spirit_affection_id_start + 141,
    "Get Growleen to Affection LV2": spirit_affection_id_start + 142,
    "Get Growleen to Affection LV3": spirit_affection_id_start + 143,
    "Get Growleen to Affection LV4": spirit_affection_id_start + 144,
    "Get Growleen to Affection LV5": spirit_affection_id_start + 145,
    "Get Gloreen to Affection LV1": spirit_affection_id_start + 146,
    "Get Gloreen to Affection LV2": spirit_affection_id_start + 147,
    "Get Gloreen to Affection LV3": spirit_affection_id_start + 148,
    "Get Gloreen to Affection LV4": spirit_affection_id_start + 149,
    "Get Gloreen to Affection LV5": spirit_affection_id_start + 150,
    "Get Bellend to Affection LV1": spirit_affection_id_start + 151,
    "Get Bellend to Affection LV2": spirit_affection_id_start + 152,
    "Get Bellend to Affection LV3": spirit_affection_id_start + 153,
    "Get Bellend to Affection LV4": spirit_affection_id_start + 154,
    "Get Bellend to Affection LV5": spirit_affection_id_start + 155,
    "Get Kittypus to Affection LV1": spirit_affection_id_start + 156,
    "Get Kittypus to Affection LV2": spirit_affection_id_start + 157,
    "Get Kittypus to Affection LV3": spirit_affection_id_start + 158,
    "Get Kittypus to Affection LV4": spirit_affection_id_start + 159,
    "Get Kittypus to Affection LV5": spirit_affection_id_start + 160,
    "Get Dripsy to Affection LV1": spirit_affection_id_start + 161,
    "Get Dripsy to Affection LV2": spirit_affection_id_start + 162,
    "Get Dripsy to Affection LV3": spirit_affection_id_start + 163,
    "Get Dripsy to Affection LV4": spirit_affection_id_start + 164,
    "Get Dripsy to Affection LV5": spirit_affection_id_start + 165,
    "Get Octocunt to Affection LV1": spirit_affection_id_start + 166,
    "Get Octocunt to Affection LV2": spirit_affection_id_start + 167,
    "Get Octocunt to Affection LV3": spirit_affection_id_start + 168,
    "Get Octocunt to Affection LV4": spirit_affection_id_start + 169,
    "Get Octocunt to Affection LV5": spirit_affection_id_start + 170,
    "Get Harlie to Affection LV1": spirit_affection_id_start + 171,
    "Get Harlie to Affection LV2": spirit_affection_id_start + 172,
    "Get Harlie to Affection LV3": spirit_affection_id_start + 173,
    "Get Harlie to Affection LV4": spirit_affection_id_start + 174,
    "Get Harlie to Affection LV5": spirit_affection_id_start + 175,
    "Get Domina to Affection LV1": spirit_affection_id_start + 176,
    "Get Domina to Affection LV2": spirit_affection_id_start + 177,
    "Get Domina to Affection LV3": spirit_affection_id_start + 178,
    "Get Domina to Affection LV4": spirit_affection_id_start + 179,
    "Get Domina to Affection LV5": spirit_affection_id_start + 180,
    "Get Dracoomer to Affection LV1": spirit_affection_id_start + 181,
    "Get Dracoomer to Affection LV2": spirit_affection_id_start + 182,
    "Get Dracoomer to Affection LV3": spirit_affection_id_start + 183,
    "Get Dracoomer to Affection LV4": spirit_affection_id_start + 184,
    "Get Dracoomer to Affection LV5": spirit_affection_id_start + 185,
    "Get Bearboo to Affection LV1": spirit_affection_id_start + 186,
    "Get Bearboo to Affection LV2": spirit_affection_id_start + 187,
    "Get Bearboo to Affection LV3": spirit_affection_id_start + 188,
    "Get Bearboo to Affection LV4": spirit_affection_id_start + 189,
    "Get Bearboo to Affection LV5": spirit_affection_id_start + 190,
    "Get Megaboob to Affection LV1": spirit_affection_id_start + 191,
    "Get Megaboob to Affection LV2": spirit_affection_id_start + 192,
    "Get Megaboob to Affection LV3": spirit_affection_id_start + 193,
    "Get Megaboob to Affection LV4": spirit_affection_id_start + 194,
    "Get Megaboob to Affection LV5": spirit_affection_id_start + 195,
    "Get Thiccsie to Affection LV1": spirit_affection_id_start + 196,
    "Get Thiccsie to Affection LV2": spirit_affection_id_start + 197,
    "Get Thiccsie to Affection LV3": spirit_affection_id_start + 198,
    "Get Thiccsie to Affection LV4": spirit_affection_id_start + 199,
    "Get Thiccsie to Affection LV5": spirit_affection_id_start + 200,
    "Get Sexybun to Affection LV1": spirit_affection_id_start + 201,
    "Get Sexybun to Affection LV2": spirit_affection_id_start + 202,
    "Get Sexybun to Affection LV3": spirit_affection_id_start + 203,
    "Get Sexybun to Affection LV4": spirit_affection_id_start + 204,
    "Get Sexybun to Affection LV5": spirit_affection_id_start + 205,
    "Get Mamaoak to Affection LV1": spirit_affection_id_start + 206,
    "Get Mamaoak to Affection LV2": spirit_affection_id_start + 207,
    "Get Mamaoak to Affection LV3": spirit_affection_id_start + 208,
    "Get Mamaoak to Affection LV4": spirit_affection_id_start + 209,
    "Get Mamaoak to Affection LV5": spirit_affection_id_start + 210,
    "Get Pinchie to Affection LV1": spirit_affection_id_start + 211,
    "Get Pinchie to Affection LV2": spirit_affection_id_start + 212,
    "Get Pinchie to Affection LV3": spirit_affection_id_start + 213,
    "Get Pinchie to Affection LV4": spirit_affection_id_start + 214,
    "Get Pinchie to Affection LV5": spirit_affection_id_start + 215,
    "Get Marinel to Affection LV1": spirit_affection_id_start + 216,
    "Get Marinel to Affection LV2": spirit_affection_id_start + 217,
    "Get Marinel to Affection LV3": spirit_affection_id_start + 218,
    "Get Marinel to Affection LV4": spirit_affection_id_start + 219,
    "Get Marinel to Affection LV5": spirit_affection_id_start + 220,
    "Get Udderella to Affection LV1": spirit_affection_id_start + 221,
    "Get Udderella to Affection LV2": spirit_affection_id_start + 222,
    "Get Udderella to Affection LV3": spirit_affection_id_start + 223,
    "Get Udderella to Affection LV4": spirit_affection_id_start + 224,
    "Get Udderella to Affection LV5": spirit_affection_id_start + 225,
    "Get Sharky to Affection LV1": spirit_affection_id_start + 226,
    "Get Sharky to Affection LV2": spirit_affection_id_start + 227,
    "Get Sharky to Affection LV3": spirit_affection_id_start + 228,
    "Get Sharky to Affection LV4": spirit_affection_id_start + 229,
    "Get Sharky to Affection LV5": spirit_affection_id_start + 230,
    "Get Faerie to Affection LV1": spirit_affection_id_start + 231,
    "Get Faerie to Affection LV2": spirit_affection_id_start + 232,
    "Get Faerie to Affection LV3": spirit_affection_id_start + 233,
    "Get Faerie to Affection LV4": spirit_affection_id_start + 234,
    "Get Faerie to Affection LV5": spirit_affection_id_start + 235,
    "Get Twerqueen to Affection LV1": spirit_affection_id_start + 236,
    "Get Twerqueen to Affection LV2": spirit_affection_id_start + 237,
    "Get Twerqueen to Affection LV3": spirit_affection_id_start + 238,
    "Get Twerqueen to Affection LV4": spirit_affection_id_start + 239,
    "Get Twerqueen to Affection LV5": spirit_affection_id_start + 240,
    "Get Chocostar to Affection LV1": spirit_affection_id_start + 241,
    "Get Chocostar to Affection LV2": spirit_affection_id_start + 242,
    "Get Chocostar to Affection LV3": spirit_affection_id_start + 243,
    "Get Chocostar to Affection LV4": spirit_affection_id_start + 244,
    "Get Chocostar to Affection LV5": spirit_affection_id_start + 245,
    "Get Amazona to Affection LV1": spirit_affection_id_start + 246,
    "Get Amazona to Affection LV2": spirit_affection_id_start + 247,
    "Get Amazona to Affection LV3": spirit_affection_id_start + 248,
    "Get Amazona to Affection LV4": spirit_affection_id_start + 249,
    "Get Amazona to Affection LV5": spirit_affection_id_start + 250,
    "Get Jellygal to Affection LV1": spirit_affection_id_start + 251,
    "Get Jellygal to Affection LV2": spirit_affection_id_start + 252,
    "Get Jellygal to Affection LV3": spirit_affection_id_start + 253,
    "Get Jellygal to Affection LV4": spirit_affection_id_start + 254,
    "Get Jellygal to Affection LV5": spirit_affection_id_start + 255,
    "Get Harpie to Affection LV1": spirit_affection_id_start + 256,
    "Get Harpie to Affection LV2": spirit_affection_id_start + 257,
    "Get Harpie to Affection LV3": spirit_affection_id_start + 258,
    "Get Harpie to Affection LV4": spirit_affection_id_start + 259,
    "Get Harpie to Affection LV5": spirit_affection_id_start + 260,
    "Get Arachna to Affection LV1": spirit_affection_id_start + 261,
    "Get Arachna to Affection LV2": spirit_affection_id_start + 262,
    "Get Arachna to Affection LV3": spirit_affection_id_start + 263,
    "Get Arachna to Affection LV4": spirit_affection_id_start + 264,
    "Get Arachna to Affection LV5": spirit_affection_id_start + 265,
    "Get Succubae to Affection LV1": spirit_affection_id_start + 266,
    "Get Succubae to Affection LV2": spirit_affection_id_start + 267,
    "Get Succubae to Affection LV3": spirit_affection_id_start + 268,
    "Get Succubae to Affection LV4": spirit_affection_id_start + 269,
    "Get Succubae to Affection LV5": spirit_affection_id_start + 270,
    "Get Panthera to Affection LV1": spirit_affection_id_start + 271,
    "Get Panthera to Affection LV2": spirit_affection_id_start + 272,
    "Get Panthera to Affection LV3": spirit_affection_id_start + 273,
    "Get Panthera to Affection LV4": spirit_affection_id_start + 274,
    "Get Panthera to Affection LV5": spirit_affection_id_start + 275,
    "Get Boobarella to Affection LV1": spirit_affection_id_start + 276,
    "Get Boobarella to Affection LV2": spirit_affection_id_start + 277,
    "Get Boobarella to Affection LV3": spirit_affection_id_start + 278,
    "Get Boobarella to Affection LV4": spirit_affection_id_start + 279,
    "Get Boobarella to Affection LV5": spirit_affection_id_start + 280,
    "Get Octomommy to Affection LV1": spirit_affection_id_start + 281,
    "Get Octomommy to Affection LV2": spirit_affection_id_start + 282,
    "Get Octomommy to Affection LV3": spirit_affection_id_start + 283,
    "Get Octomommy to Affection LV4": spirit_affection_id_start + 284,
    "Get Octomommy to Affection LV5": spirit_affection_id_start + 285,
    "Get Queenbee to Affection LV1": spirit_affection_id_start + 286,
    "Get Queenbee to Affection LV2": spirit_affection_id_start + 287,
    "Get Queenbee to Affection LV3": spirit_affection_id_start + 288,
    "Get Queenbee to Affection LV4": spirit_affection_id_start + 289,
    "Get Queenbee to Affection LV5": spirit_affection_id_start + 290,
    "Get Gangfang to Affection LV1": spirit_affection_id_start + 291,
    "Get Gangfang to Affection LV2": spirit_affection_id_start + 292,
    "Get Gangfang to Affection LV3": spirit_affection_id_start + 293,
    "Get Gangfang to Affection LV4": spirit_affection_id_start + 294,
    "Get Gangfang to Affection LV5": spirit_affection_id_start + 295,
    "Get Jawsy to Affection LV1": spirit_affection_id_start + 296,
    "Get Jawsy to Affection LV2": spirit_affection_id_start + 297,
    "Get Jawsy to Affection LV3": spirit_affection_id_start + 298,
    "Get Jawsy to Affection LV4": spirit_affection_id_start + 299,
    "Get Jawsy to Affection LV5": spirit_affection_id_start + 300,
    "Get Polaria to Affection LV1": spirit_affection_id_start + 301,
    "Get Polaria to Affection LV2": spirit_affection_id_start + 302,
    "Get Polaria to Affection LV3": spirit_affection_id_start + 303,
    "Get Polaria to Affection LV4": spirit_affection_id_start + 304,
    "Get Polaria to Affection LV5": spirit_affection_id_start + 305,
    "Get Slithereen to Affection LV1": spirit_affection_id_start + 306,
    "Get Slithereen to Affection LV2": spirit_affection_id_start + 307,
    "Get Slithereen to Affection LV3": spirit_affection_id_start + 308,
    "Get Slithereen to Affection LV4": spirit_affection_id_start + 309,
    "Get Slithereen to Affection LV5": spirit_affection_id_start + 310,
    "Get Jellybish to Affection LV1": spirit_affection_id_start + 311,
    "Get Jellybish to Affection LV2": spirit_affection_id_start + 312,
    "Get Jellybish to Affection LV3": spirit_affection_id_start + 313,
    "Get Jellybish to Affection LV4": spirit_affection_id_start + 314,
    "Get Jellybish to Affection LV5": spirit_affection_id_start + 315,
    "Get Valkyrie to Affection LV1": spirit_affection_id_start + 316,
    "Get Valkyrie to Affection LV2": spirit_affection_id_start + 317,
    "Get Valkyrie to Affection LV3": spirit_affection_id_start + 318,
    "Get Valkyrie to Affection LV4": spirit_affection_id_start + 319,
    "Get Valkyrie to Affection LV5": spirit_affection_id_start + 320,
    "Get Slushie to Affection LV1": spirit_affection_id_start + 321,
    "Get Slushie to Affection LV2": spirit_affection_id_start + 322,
    "Get Slushie to Affection LV3": spirit_affection_id_start + 323,
    "Get Slushie to Affection LV4": spirit_affection_id_start + 324,
    "Get Slushie to Affection LV5": spirit_affection_id_start + 325,
    "Get Deardeer to Affection LV1": spirit_affection_id_start + 326,
    "Get Deardeer to Affection LV2": spirit_affection_id_start + 327,
    "Get Deardeer to Affection LV3": spirit_affection_id_start + 328,
    "Get Deardeer to Affection LV4": spirit_affection_id_start + 329,
    "Get Deardeer to Affection LV5": spirit_affection_id_start + 330,
    "Get Snowbae to Affection LV1": spirit_affection_id_start + 331,
    "Get Snowbae to Affection LV2": spirit_affection_id_start + 332,
    "Get Snowbae to Affection LV3": spirit_affection_id_start + 333,
    "Get Snowbae to Affection LV4": spirit_affection_id_start + 334,
    "Get Snowbae to Affection LV5": spirit_affection_id_start + 335,
    "Get Unihorn to Affection LV1": spirit_affection_id_start + 336,
    "Get Unihorn to Affection LV2": spirit_affection_id_start + 337,
    "Get Unihorn to Affection LV3": spirit_affection_id_start + 338,
    "Get Unihorn to Affection LV4": spirit_affection_id_start + 339,
    "Get Unihorn to Affection LV5": spirit_affection_id_start + 340,
    "Get Fungie to Affection LV1": spirit_affection_id_start + 341,
    "Get Fungie to Affection LV2": spirit_affection_id_start + 342,
    "Get Fungie to Affection LV3": spirit_affection_id_start + 343,
    "Get Fungie to Affection LV4": spirit_affection_id_start + 344,
    "Get Fungie to Affection LV5": spirit_affection_id_start + 345,
    "Get Lizzie to Affection LV1": spirit_affection_id_start + 346,
    "Get Lizzie to Affection LV2": spirit_affection_id_start + 347,
    "Get Lizzie to Affection LV3": spirit_affection_id_start + 348,
    "Get Lizzie to Affection LV4": spirit_affection_id_start + 349,
    "Get Lizzie to Affection LV5": spirit_affection_id_start + 350,
    "Get Juggsie to Affection LV1": spirit_affection_id_start + 351,
    "Get Juggsie to Affection LV2": spirit_affection_id_start + 352,
    "Get Juggsie to Affection LV3": spirit_affection_id_start + 353,
    "Get Juggsie to Affection LV4": spirit_affection_id_start + 354,
    "Get Juggsie to Affection LV5": spirit_affection_id_start + 355,
    "Get Dominatrix to Affection LV1": spirit_affection_id_start + 356,
    "Get Dominatrix to Affection LV2": spirit_affection_id_start + 357,
    "Get Dominatrix to Affection LV3": spirit_affection_id_start + 358,
    "Get Dominatrix to Affection LV4": spirit_affection_id_start + 359,
    "Get Dominatrix to Affection LV5": spirit_affection_id_start + 360,
    "Get Seraphina to Affection LV1": spirit_affection_id_start + 361,
    "Get Seraphina to Affection LV2": spirit_affection_id_start + 362,
    "Get Seraphina to Affection LV3": spirit_affection_id_start + 363,
    "Get Seraphina to Affection LV4": spirit_affection_id_start + 364,
    "Get Seraphina to Affection LV5": spirit_affection_id_start + 365,
    "Get Centiboob to Affection LV1": spirit_affection_id_start + 366,
    "Get Centiboob to Affection LV2": spirit_affection_id_start + 367,
    "Get Centiboob to Affection LV3": spirit_affection_id_start + 368,
    "Get Centiboob to Affection LV4": spirit_affection_id_start + 369,
    "Get Centiboob to Affection LV5": spirit_affection_id_start + 370,
    "Get EV-3 to Affection LV1": spirit_affection_id_start + 371,
    "Get EV-3 to Affection LV2": spirit_affection_id_start + 372,
    "Get EV-3 to Affection LV3": spirit_affection_id_start + 373,
    "Get EV-3 to Affection LV4": spirit_affection_id_start + 374,
    "Get EV-3 to Affection LV5": spirit_affection_id_start + 375,
}

Rare_spirit_id_start = spirit_affection_id_start + 375
Rare_spirit_locations = {
    "Obtain a Rare Pusseen Spirit": Rare_spirit_id_start + 1,
    "Obtain a Rare Boobae Spirit": Rare_spirit_id_start + 2,
    "Obtain a Rare Octopussy Spirit": Rare_spirit_id_start + 3,
    "Obtain a Rare Petunia Spirit": Rare_spirit_id_start + 4,
    "Obtain a Rare Beebee Spirit": Rare_spirit_id_start + 5,
    "Obtain a Rare Slimee Spirit": Rare_spirit_id_start + 6,
    "Obtain a Rare Wolfy Spirit": Rare_spirit_id_start + 7,
    "Obtain a Rare Ursie Spirit": Rare_spirit_id_start + 8,
    "Obtain a Rare Gloria Spirit": Rare_spirit_id_start + 9,
    "Obtain a Rare Serpentina Spirit": Rare_spirit_id_start + 10,
    "Obtain a Rare Belle Spirit": Rare_spirit_id_start + 11,
    "Obtain a Rare Oakie Spirit": Rare_spirit_id_start + 12,
    "Obtain a Rare Trissy Spirit": Rare_spirit_id_start + 13,
    "Obtain a Rare Spinnie Spirit": Rare_spirit_id_start + 14,
    "Obtain a Rare Chubbie Spirit": Rare_spirit_id_start + 15,
    "Obtain a Rare Bunni Spirit": Rare_spirit_id_start + 16,
    "Obtain a Rare Tinky Spirit": Rare_spirit_id_start + 17,
    "Obtain a Rare Rawry Spirit": Rare_spirit_id_start + 18,
    "Obtain a Rare Serpentax Spirit": Rare_spirit_id_start + 19,
    "Obtain a Rare Birdy Spirit": Rare_spirit_id_start + 20,
    "Obtain a Rare Cactee Spirit": Rare_spirit_id_start + 21,
    "Obtain a Rare Twerky Spirit": Rare_spirit_id_start + 22,
    "Obtain a Rare Bovina Spirit": Rare_spirit_id_start + 23,
    "Obtain a Rare Lacteena Spirit": Rare_spirit_id_start + 24,
    "Obtain a Rare Hornie Spirit": Rare_spirit_id_start + 25,
    "Obtain a Rare Buzzeena Spirit": Rare_spirit_id_start + 26,
    "Obtain a Rare Triboobe Spirit": Rare_spirit_id_start + 27,
    "Obtain a Rare Flora Spirit": Rare_spirit_id_start + 28,
    "Obtain a Rare Growleen Spirit": Rare_spirit_id_start + 29,
    "Obtain a Rare Gloreen Spirit": Rare_spirit_id_start + 30,
    "Obtain a Rare Bellend Spirit": Rare_spirit_id_start + 31,
    "Obtain a Rare Kittypus Spirit": Rare_spirit_id_start + 32,
    "Obtain a Rare Dripsy Spirit": Rare_spirit_id_start + 33,
    "Obtain a Rare Octocunt Spirit": Rare_spirit_id_start + 34,
    "Obtain a Rare Harlie Spirit": Rare_spirit_id_start + 35,
    "Obtain a Rare Domina Spirit": Rare_spirit_id_start + 36,
    "Obtain a Rare Dracoomer Spirit": Rare_spirit_id_start + 37,
    "Obtain a Rare Bearboo Spirit": Rare_spirit_id_start + 38,
    "Obtain a Rare Megaboob Spirit": Rare_spirit_id_start + 39,
    "Obtain a Rare Thiccsie Spirit": Rare_spirit_id_start + 40,
    "Obtain a Rare Sexybun Spirit": Rare_spirit_id_start + 41,
    "Obtain a Rare Mamaoak Spirit": Rare_spirit_id_start + 42,
    "Obtain a Rare Pinchie Spirit": Rare_spirit_id_start + 43,
    "Obtain a Rare Marinel Spirit": Rare_spirit_id_start + 44,
    "Obtain a Rare Udderella Spirit": Rare_spirit_id_start + 45,
    "Obtain a Rare Sharky Spirit": Rare_spirit_id_start + 46,
    "Obtain a Rare Faerie Spirit": Rare_spirit_id_start + 47,
    "Obtain a Rare Twerqueen Spirit": Rare_spirit_id_start + 48,
    "Obtain a Rare Chocostar Spirit": Rare_spirit_id_start + 49,
    "Obtain a Rare Amazona Spirit": Rare_spirit_id_start + 50,
    "Obtain a Rare Jellygal Spirit": Rare_spirit_id_start + 51,
    "Obtain a Rare Harpie Spirit": Rare_spirit_id_start + 52,
    "Obtain a Rare Arachna Spirit": Rare_spirit_id_start + 53,
    "Obtain a Rare Succubae Spirit": Rare_spirit_id_start + 54,
    "Obtain a Rare Panthera Spirit": Rare_spirit_id_start + 55,
    "Obtain a Rare Boobarella Spirit": Rare_spirit_id_start + 56,
    "Obtain a Rare Octomommy Spirit": Rare_spirit_id_start + 57,
    "Obtain a Rare Queenbee Spirit": Rare_spirit_id_start + 58,
    "Obtain a Rare Gangfang Spirit": Rare_spirit_id_start + 59,
    "Obtain a Rare Jawsy Spirit": Rare_spirit_id_start + 60,
    "Obtain a Rare Polaria Spirit": Rare_spirit_id_start + 61,
    "Obtain a Rare Slithereen Spirit": Rare_spirit_id_start + 62,
    "Obtain a Rare Jellybish Spirit": Rare_spirit_id_start + 63,
    "Obtain a Rare Valkyrie Spirit": Rare_spirit_id_start + 64,
    "Obtain a Rare Slushie Spirit": Rare_spirit_id_start + 65,
    "Obtain a Rare Deardeer Spirit": Rare_spirit_id_start + 66,
    "Obtain a Rare Snowbae Spirit": Rare_spirit_id_start + 67,
    "Obtain a Rare Unihorn Spirit": Rare_spirit_id_start + 68,
    "Obtain a Rare Fungie Spirit": Rare_spirit_id_start + 69,
    "Obtain a Rare Lizzie Spirit": Rare_spirit_id_start + 70,
    "Obtain a Rare Juggsie Spirit": Rare_spirit_id_start + 71,
    "Obtain a Rare Dominatrix Spirit": Rare_spirit_id_start + 72,
    "Obtain a Rare Seraphina Spirit": Rare_spirit_id_start + 73,
    "Obtain a Rare Centiboob Spirit": Rare_spirit_id_start + 74,
    "Obtain a Rare EV-3 Spirit": Rare_spirit_id_start + 75,
}

main_quests_id_start = Rare_spirit_id_start + 75  # add spirit locations
main_quests = {
    "Complete Main Quest: Doctor’s Appointment": main_quests_id_start + 1,  # Oakwood Village
    "Complete Main Quest: Captain Maria": main_quests_id_start + 2,  # Oakwood Village
    "Complete Main Quest: First Orders": main_quests_id_start + 3,  # Evergreen Outpost
    "Complete Main Quest: Crimson Agent": main_quests_id_start + 4,  # Trail 02
    "Complete Main Quest: Super Secret Orders": main_quests_id_start + 5,  # Evergreen Outpost
    "Complete Main Quest: First Mission: Success!": main_quests_id_start + 6,  # Oakwood Village
    "Complete Main Quest: Onward to Greensvale": main_quests_id_start + 7,  # Greensvale
    "Complete Main Quest: Temple Investigation": main_quests_id_start + 8,  # Ancient Temple
    "Complete Main Quest: Harmonious Disturbance": main_quests_id_start + 9,  # Greensvale
    "Complete Main Quest: Consulting Dolly": main_quests_id_start + 10,  # Oakwood Village
    "Complete Main Quest: Becky can fix it": main_quests_id_start + 11,  # Greensvale
    "Complete Main Quest: Hunt for the chunk": main_quests_id_start + 12,  # Greensvale
    "Complete Main Quest: Bridge crossing": main_quests_id_start + 13,  # Evergreen Outpost
    "Complete Main Quest: Dusty Vale awaits": main_quests_id_start + 14,  # Tumbleweed Town
    "Complete Main Quest: An audience with the King": main_quests_id_start + 15,  # Tumbleweed Town
    "Complete Main Quest: The Grand Cuckold Challenge": main_quests_id_start + 16,  # Tumbleweed Town
    "Complete Main Quest: License to battle": main_quests_id_start + 17,  # Old Masters Hut
    "Complete Main Quest: Box pusher": main_quests_id_start + 18,  # Old Masters Hut
    "Complete Main Quest: Total domination": main_quests_id_start + 19,  # Old Masters Hut
    "Complete Main Quest: A challenge awaits": main_quests_id_start + 20,  # Tumbleweed Town
    "Complete Main Quest: A new challenger": main_quests_id_start + 21,  # Tumbleweed Town
    "Complete Main Quest: Stiff competition": main_quests_id_start + 22,  # Tumbleweed Town
    "Complete Main Quest: Final Fight": main_quests_id_start + 23,  # Tumbleweed Town
    "Complete Main Quest: Return of the champion": main_quests_id_start + 24,  # Tumbleweed Town
    "Complete Main Quest: Breeding season": main_quests_id_start + 25,  # Tumbleweed Town
    "Complete Main Quest: Mission success": main_quests_id_start + 26,  # Tumbleweed Town
    "Complete Main Quest: Quest for the crystal": main_quests_id_start + 27,  # stone temple
    "Complete Main Quest: How the Dominoes fall": main_quests_id_start + 28,  # Tumbleweed Town
    "Complete Main Quest: Big balloon adventure": main_quests_id_start + 29,  # Tumbleweed Town
    "Complete Main Quest: Welcome to Paradise": main_quests_id_start + 30,  # Coconut Village
    "Complete Main Quest: Coconut Conundrum": main_quests_id_start + 31,  # Trail 13
    "Complete Main Quest: Lusty Cultists": main_quests_id_start + 32,  # Island Cave
    "Complete Main Quest: Savior of Coconut Village": main_quests_id_start + 33,  # Coconut Village
    "Complete Main Quest: Slippery When Wet": main_quests_id_start + 34,  # Coconut Village
    "Complete Main Quest: Glimmering Prize": main_quests_id_start + 35,  # Coconut Village
    "Complete Main Quest: Arctic Adventure": main_quests_id_start + 36,  # Coconut Village
    "Complete Main Quest: The Frigid Maiden": main_quests_id_start + 37,  # Cold Harbor
    "Complete Main Quest: Arctic Isles": main_quests_id_start + 38,  # Frostville
    "Complete Main Quest: Paisley Bones": main_quests_id_start + 39,  # Frostville
    "Complete Main Quest: Demand for Dynamite": main_quests_id_start + 40,  # Abandoned Mine
    "Complete Main Quest: Stealing From a Dead Man": main_quests_id_start + 41,  # Frostville
    "Complete Main Quest: The Lewd Exorcist": main_quests_id_start + 42,  # Frostville
    "Complete Main Quest: Suit In Hand": main_quests_id_start + 43,  # Abandoned Mine
    "Complete Main Quest: Fishing For Treasure": main_quests_id_start + 44,  # Abandoned Mine
    "Complete Main Quest: The Proposal": main_quests_id_start + 45,  # Frostville
    "Complete Main Quest: Here Comes the Boom": main_quests_id_start + 46,  # Frostville
    "Complete Main Quest: Arctic Harmony": main_quests_id_start + 47,  # Artic Temple
    "Complete Main Quest: Crimson Chase": main_quests_id_start + 48,  # Trail 18
    "Complete Main Quest: Through the Portal": main_quests_id_start + 49,  #
    "Complete Main Quest: Sanctuary Shakedown": main_quests_id_start + 50,  #
    "Complete Main Quest: Hostage Situation": main_quests_id_start + 51,  #
    "Complete Main Quest: Breezie Runs Free": main_quests_id_start + 52,  #
    "Complete Main Quest: Desperate Dash": main_quests_id_start + 53,  #
    "Complete Main Quest: Battle for Spirit Valley": main_quests_id_start + 54,  #
    #"Complete Main Quest: Through the Portal": main_quests_id_start + 55,  #
}

side_quests_id_start = main_quests_id_start + 54
side_quests = {
    "Complete Side Quest: Sparring Match": side_quests_id_start + 1,
    "Complete Side Quest: Larry’s Treasure": side_quests_id_start + 2,
    "Complete Side Quest: Perky Petunia": side_quests_id_start + 3,
    "Complete Side Quest: Pleasuring Pusseen": side_quests_id_start + 4,
    "Complete Side Quest: Slithering Menace": side_quests_id_start + 5,
    "Complete Side Quest: Cattle Thieves": side_quests_id_start + 6,
    "Complete Side Quest: Professional Pleasurer": side_quests_id_start + 7,
    "Complete Side Quest: Fishy Duel": side_quests_id_start + 8,
    "Complete Side Quest: The Art of Fishing": side_quests_id_start + 9,
    "Complete Side Quest: Fishmaster’s Challenge": side_quests_id_start + 10,
    "Complete Side Quest: Deadly Waters": side_quests_id_start + 11,
    "Complete Side Quest: Starry Eyed Surprise": side_quests_id_start + 12,
    "Complete Side Quest: Arctic Menace": side_quests_id_start + 13,
    "Complete Side Quest: Legend of the Valkyrie part 1.": side_quests_id_start + 14,
    "Complete Side Quest: Legend of the Valkyrie part 2.": side_quests_id_start + 15,
    "Complete Side Quest: Hunt for the Centiboob part 1.": side_quests_id_start + 16,
    "Complete Side Quest: Hunt for the Centiboob part 2.": side_quests_id_start + 17,
    "Complete Side Quest: Hunt for the Centiboob part 3.": side_quests_id_start + 18,
}

battle_locations_id_start = side_quests_id_start + 18
battle_locations = {
    "Oakwood Village: Defeat Robbie": battle_locations_id_start + 1,
    "Evergreen Outpost: Defeat Elise": battle_locations_id_start + 2,
    "Trail 02: Defeat Billy": battle_locations_id_start + 3,
    "Trail 02: Defeat Macy": battle_locations_id_start + 4,
    "Trail 02: Defeat Skyler": battle_locations_id_start + 5,
    "Trail 02: Defeat Crimson Agent": battle_locations_id_start + 6,
    "Trail 03: Defeat Cheese": battle_locations_id_start + 7,
    "Trail 03: Defeat Miriam": battle_locations_id_start + 8,
    "Trail 03: Defeat Jenna": battle_locations_id_start + 9,
    "Evergreen Caverns: Defeat Stu": battle_locations_id_start + 10,
    "Evergreen Caverns: Defeat Nicole": battle_locations_id_start + 11,
    "Evergreen Caverns: Defeat Rawry": battle_locations_id_start + 12,
    "Ancient Temple 1: Defeat 1st Crimson Cloak": battle_locations_id_start + 13,
    "Ancient Temple 1: Defeat 2nd Crimson Cloak": battle_locations_id_start + 14,
    "Ancient Temple 1: Defeat 3rd Crimson Cloak": battle_locations_id_start + 15,
    "Ancient Temple 1: Defeat 4th Crimson Cloak": battle_locations_id_start + 16,
    "Ancient Temple 1: Defeat 5th Crimson Cloak": battle_locations_id_start + 17,
    "Ancient Temple 1: Defeat 6th Crimson Cloak": battle_locations_id_start + 18,
    "Ancient Temple 2: Defeat Crimson Cloak": battle_locations_id_start + 19,
    "Ancient Temple 3: Defeat Valkrie": battle_locations_id_start + 20,
    "Trail 05: Defeat Mila": battle_locations_id_start + 21,
    "Trail 05: Defeat Roy": battle_locations_id_start + 22,
    "Trail 05: Defeat Lulu": battle_locations_id_start + 23,
    "Sandy Tunnels: Defeat Chad": battle_locations_id_start + 24,
    "Sandy Tunnels: Defeat Destiny": battle_locations_id_start + 25,
    "Trail 06: Defeat Kelsie": battle_locations_id_start + 26,
    "Trail 06: Defeat Hayden": battle_locations_id_start + 27,
    "Trail 06: Defeat Juliet": battle_locations_id_start + 28,
    "Trail 07: Defeat Sally McTits": battle_locations_id_start + 29,
    "Trail 07: Defeat Bella": battle_locations_id_start + 30,
    "Trail 07: Defeat Dakota": battle_locations_id_start + 31,
    "Trail 07: Defeat Cassidy": battle_locations_id_start + 32,
    "Tumbleweed Town: Defeat Willy Wanker": battle_locations_id_start + 33,
    "Tumbleweed Town: Defeat Dick Cummings": battle_locations_id_start + 34,
    "Tumbleweed Town: Defeat Dick Louie": battle_locations_id_start + 35,
    "Trail 08: Defeat Marisa": battle_locations_id_start + 36,
    "Trail 08: Defeat Jenni": battle_locations_id_start + 37,
    "Trail 08: Defeat Alanna": battle_locations_id_start + 38,
    "Dusty Grotto: Defeat Arnie": battle_locations_id_start + 39,
    "Dusty Grotto: Defeat Crystal": battle_locations_id_start + 40,
    "Dusty Grotto: Defeat Skye": battle_locations_id_start + 41,
    "Trail 09: Defeat Mike": battle_locations_id_start + 42,
    "Trail 09: Defeat Clementine": battle_locations_id_start + 43,
    "Trail 09: Defeat Bonnie": battle_locations_id_start + 44,
    "Stone Temple 1: Defeat 1st Crimson Cloak": battle_locations_id_start + 45,
    "Stone Temple 1: Defeat 2nd Crimson Cloak": battle_locations_id_start + 46,
    "Stone Temple 1: Defeat 3rd Crimson Cloak": battle_locations_id_start + 47,
    "Stone Temple 1: Defeat 4th Crimson Cloak": battle_locations_id_start + 48,
    "Stone Temple 1: Defeat 5th Crimson Cloak": battle_locations_id_start + 49,
    "Stone Temple 1: Defeat 6th Crimson Cloak": battle_locations_id_start + 50,
    "Stone Temple 2: Defeat Domino": battle_locations_id_start + 51,
    "Crash Site: Defeat Athena": battle_locations_id_start + 52,
    "Crash Site: Defeat Janet": battle_locations_id_start + 53,
    "Trail 10: Defeat Bailee": battle_locations_id_start + 54,
    "Trail 10: Defeat Eve": battle_locations_id_start + 55,
    "Trail 11: Defeat Alice": battle_locations_id_start + 56,
    "Trail 11: Defeat Emilia": battle_locations_id_start + 57,
    "Trail 11: Defeat Sydney": battle_locations_id_start + 58,
    "Trail 12: Defeat Sophie": battle_locations_id_start + 59,
    "Trail 12: Defeat Ciara": battle_locations_id_start + 60,
    "Fishing Hut: Defeat Bonnie Baiter": battle_locations_id_start + 61,
    "Trail 13: Defeat 1st Cultist": battle_locations_id_start + 62,
    "Trail 13: Defeat 2nd Cultist": battle_locations_id_start + 63,
    "Trail 14: Defeat 1st Cultist": battle_locations_id_start + 64,
    "Trail 14: Defeat 2nd Cultist": battle_locations_id_start + 65,
    "Island Cave 1: Defeat 1st Cultist": battle_locations_id_start + 66,
    "Island Cave 1: Defeat 2nd Cultist": battle_locations_id_start + 67,
    "Island Cave 1: Defeat 3rd Cultist": battle_locations_id_start + 68,
    "Island Cave 1: Defeat 4th Cultist": battle_locations_id_start + 69,
    "Island Cave 2: Defeat Centiboob": battle_locations_id_start + 70,
    "Cold Harbour: Defeat Vanessa": battle_locations_id_start + 71,
    "Cold Harbour: Defeat Iris": battle_locations_id_start + 72,
    "Frostville: Defeat Mother Evilyn": battle_locations_id_start + 73,
    "Trail 15: Defeat Mia": battle_locations_id_start + 74,
    "Trail 15: Defeat Olga": battle_locations_id_start + 75,
    "Trail 16: Defeat Karin": battle_locations_id_start + 76,
    "Trail 16: Defeat Dahlia": battle_locations_id_start + 77,
    "Trail 17: Defeat Clara": battle_locations_id_start + 78,
    "Trail 17: Defeat Liv": battle_locations_id_start + 79,
    "Trail 17: Defeat Karly": battle_locations_id_start + 80,
    "Trail 18: Defeat Stacy": battle_locations_id_start + 81,
    "Trail 18: Defeat Anabelle": battle_locations_id_start + 82,
    "Trail 18: Defeat Ingrid": battle_locations_id_start + 83,
    "Artic Temple 1: Defeat 1st Crimson Cloak": battle_locations_id_start + 84,
    "Artic Temple 1: Defeat 2nd Crimson Cloak": battle_locations_id_start + 85,
    "Artic Temple 1: Defeat 3rd Crimson Cloak": battle_locations_id_start + 86,
    "Artic Temple 1: Defeat 4th Crimson Cloak": battle_locations_id_start + 87,
    "Artic Temple 1: Defeat 5th Crimson Cloak": battle_locations_id_start + 88,
    "Artic Temple 2: Defeat Crimson Countess": battle_locations_id_start + 89,

    "Trail 19: Defeat 1st Crimson Cloak": battle_locations_id_start + 90,
    "Trail 19: Defeat 2nd Crimson Cloak": battle_locations_id_start + 91,
    "Trail 19: Defeat 3rd Crimson Cloak": battle_locations_id_start + 92,
    "Trail 20: Defeat 1st Crimson Cloak": battle_locations_id_start + 93,
    "Trail 20: Defeat 2nd Crimson Cloak": battle_locations_id_start + 94,
    "Trail 20 Right: Defeat Crimson Cloak": battle_locations_id_start + 95,
    "Trail 21: Defeat 1st Crimson Cloak": battle_locations_id_start + 96,
    "Trail 21: Defeat 2nd Crimson Cloak": battle_locations_id_start + 97,
    "Trail 21: Defeat Kinley": battle_locations_id_start + 98,
    "Trail Spirit Passage: Defeat 1st Crimson Cloak": battle_locations_id_start + 99,
    "Trail Spirit Passage: Defeat 2nd Crimson Cloak": battle_locations_id_start + 100,
    "Trail Spirit Passage: Defeat 3rd Crimson Cloak": battle_locations_id_start + 101,
    "Trail Spirit Passage: Defeat 4th Crimson Cloak": battle_locations_id_start + 102,
    "Trail Spirit Passage: Defeat 5th Crimson Cloak": battle_locations_id_start + 103,
    "Trail 22: Defeat 1st Crimson Cloak": battle_locations_id_start + 104,
    "Trail 22: Defeat 2nd Crimson Cloak": battle_locations_id_start + 105,
    "Trail 22: Defeat 3rd Crimson Cloak": battle_locations_id_start + 106,
    "Inner Grove: Defeat Spirit Mother": battle_locations_id_start + 107,
}

chest_locations_id_start = battle_locations_id_start + 107
chest_locations = {
    "Oakwood Village House: Chest House": chest_locations_id_start + 1,
    "Trail 01: Chest Near Piper": chest_locations_id_start + 2,
    "Trail 01: Chest North of Piper": chest_locations_id_start + 3,
    "Trail 01: Potion From Jane": chest_locations_id_start + 4,
    "Evergreen Outpost: Chest Near Medic": chest_locations_id_start + 5,
    "Evergreen Outpost: Chest Above Grass Patch": chest_locations_id_start + 6,
    "Evergreen Outpost: Chest Behind Pushable Bolder": chest_locations_id_start + 7,
    "Trail 02: Chest Near Billy": chest_locations_id_start + 8,
    "Trail 02: Chest in Hidden Path Next to Macy": chest_locations_id_start + 9,
    "Trail 02: Chest East of Macy": chest_locations_id_start + 10,
    "Trail 02: Chest Near Skyler": chest_locations_id_start + 11,
    "Greensvale: Chest South of Waystone": chest_locations_id_start + 12,
    "Greensvale House: Chest in House": chest_locations_id_start + 13,
    "Greensvale: Chest Next To XXX Shop": chest_locations_id_start + 14,
    "Greensvale: Chest Behind Pushable Bolder In the North": chest_locations_id_start + 15,
    "Milly's Farm: Chest Behind Pushable Bolder": chest_locations_id_start + 16,
    "Trail 03: Chest North of Miriam": chest_locations_id_start + 17,
    "Trail 03: Chest South of Miriam": chest_locations_id_start + 18,
    "Trail 03: Chest Chest Before Evergreen Caverns Entrance": chest_locations_id_start + 19,
    "Evergreen Caverns: Chest West of Stu": chest_locations_id_start + 20,
    "Evergreen Caverns: Chest South of Nicole": chest_locations_id_start + 21,
    "Evergreen Caverns: Chest 1 Behind Rawry": chest_locations_id_start + 22,
    "Evergreen Caverns: Chest 2 Behind Rawry": chest_locations_id_start + 23,
    "Trail 04: Chest West of Evergreen Caverns Entrance": chest_locations_id_start + 24,
    "Trail 04: Chest West Side of Map": chest_locations_id_start + 25,
    "Trail 04: Chest Near Waystone": chest_locations_id_start + 26,
    "Ancient Temple 1: Chest Near 3rd Crimson Cloak": chest_locations_id_start + 27,
    "Ancient Temple 1: Chest in Path Loop": chest_locations_id_start + 28,
    "Ancient Temple 1: Chest Near 6th Crimson Cloak": chest_locations_id_start + 29,
    "Ancient Temple 2: Chest West Side of Room": chest_locations_id_start + 30,
    "Ancient Temple 2: Chest East side of Room": chest_locations_id_start + 31,
    "Ancient Temple 2: Chest in Middle Area of Room": chest_locations_id_start + 32,
    "Trail 05: Chest Near Evergreen Outpost Entrance": chest_locations_id_start + 33,
    "Trail 05: Chest East of Mila": chest_locations_id_start + 34,
    "Trail 05: Chest West of Roy": chest_locations_id_start + 35,
    "Trail 05: Chest East of Lulu": chest_locations_id_start + 36,
    "Sandy Tunnels: Chest South of Chad": chest_locations_id_start + 37,
    "Sandy Tunnels: Chest North of Chad": chest_locations_id_start + 38,
    "Sandy Tunnels: Chest West of Destiny": chest_locations_id_start + 39,
    "Sandy Tunnels: Healing Potion From Jessica": chest_locations_id_start + 40,
    "Trail 06: Chest West of Sandy Tunnels Entrance": chest_locations_id_start + 41,
    "Trail 06: Chest East of Kelsie": chest_locations_id_start + 42,
    "Trail 06: Chest South of Hayden": chest_locations_id_start + 43,
    "Dairy Farm: Chest North of Waystone": chest_locations_id_start + 44,
    "Dairy Farm: Chest South of Waystone": chest_locations_id_start + 45,
    "Dairy Farm: Chest Next to House": chest_locations_id_start + 46,
    "Dairy Farm: Chest North-East of House": chest_locations_id_start + 47,
    "Trail 07: Chest Near Dairy Farm Entrance": chest_locations_id_start + 48,
    "Trail 07: Chest North of Bella": chest_locations_id_start + 49,
    "Trail 07: Chest South of Bella": chest_locations_id_start + 50,
    "Trail 07: Chest South of Dakota": chest_locations_id_start + 51,
    "Tumbleweed Town: Chest South of Town": chest_locations_id_start + 52,
    "Tumbleweed Town: Chest North-West of Town": chest_locations_id_start + 53,
    "Tumbleweed Town House: Chest in House": chest_locations_id_start + 54,
    "Trail 08: Chest West of Tumbleweed Town Entrance": chest_locations_id_start + 55,
    "Trail 08: Chest South of Marisa": chest_locations_id_start + 56,
    "Trail 08: Chest Near Dusty Grotto Entrance": chest_locations_id_start + 57,
    "Dusty Grotto: Chest Near Crystal": chest_locations_id_start + 58,
    "Dusty Grotto: Chest West of Skye": chest_locations_id_start + 59,
    "Old Masters Hut: Chest North of House": chest_locations_id_start + 60,
    "Old Masters Hut: Chest Next to House": chest_locations_id_start + 61,
    "Old Masters Hut: Chest in House": chest_locations_id_start + 62,
    "Old Masters Hut: Chest in Basement": chest_locations_id_start + 63,
    "Cave of Torment: Chest East Side of Cave": chest_locations_id_start + 64,
    "Cave of Torment: Chest North Side of Cave": chest_locations_id_start + 65,
    "Cave of Torment: Chest West Side of Cave": chest_locations_id_start + 66,
    "Trail 09: Chest near Clementine": chest_locations_id_start + 67,
    "Trail 09: Chest North of Mike": chest_locations_id_start + 68,
    "Trail 09: Chest Near Stone Temple Back Entrance Ledge": chest_locations_id_start + 69,
    "Stone Temple 1: Chest Near Trail 09 Entrence": chest_locations_id_start + 70,
    "Stone Temple 1: Chest Near 6th Crimson Cloak": chest_locations_id_start + 71,
    "Stone Temple 1: Chest Near Stone Temple 2 Entrance": chest_locations_id_start + 72,
    "Crash Site: Chest East of Athena": chest_locations_id_start + 73,
    "Crash Site: Chest West of Janet": chest_locations_id_start + 74,
    "Crash Site: Chest South of Janet": chest_locations_id_start + 75,
    "Trail 10: Chest West of Crash Site Entrance": chest_locations_id_start + 76,
    "Trail 10: Chest Near Eve": chest_locations_id_start + 77,
    "Trail 10: Chest South of Bailee": chest_locations_id_start + 78,
    "Coconut Village: Chest North-East in Village": chest_locations_id_start + 79,
    "Coconut Village: Chest East of Village": chest_locations_id_start + 80,
    "Coconut Village House: Chest in House": chest_locations_id_start + 81,
    "Coconut Village: Chest in Temple": chest_locations_id_start + 82,
    "Coconut Village: Chest In Temple After Locked Door": chest_locations_id_start + 83,
    "Trail 11: Chest Near Alice": chest_locations_id_start + 84,
    "Trail 11: Chest Near Pier": chest_locations_id_start + 85,
    "Trail 11: Chest East of Emilia": chest_locations_id_start + 86,
    "Trail 11: Chest South of Sydney": chest_locations_id_start + 87,
    "Trail 12: Chest North of Sophie": chest_locations_id_start + 88,
    "Trail 12: Chest North of Ciara": chest_locations_id_start + 89,
    "Fishing Hut: Chest North-West on the Beach": chest_locations_id_start + 90,
    "Fishing Hut: Chest Next to House": chest_locations_id_start + 91,
    "Fishing Hut: Chest East on the Beach": chest_locations_id_start + 92,
    "Fishing Hut: Chest Eastern Side of Map": chest_locations_id_start + 93,
    "Trail 13: Chest South-West of 1st Cultist": chest_locations_id_start + 94,
    "Trail 13: Chest North of 1st Cultist": chest_locations_id_start + 95,
    "Trail 14: Chest North-West of 1st Cultist": chest_locations_id_start + 96,
    "Trail 14: Chest East of 1st Cultist": chest_locations_id_start + 97,
    "Trail 14: Chest East of Waystone": chest_locations_id_start + 98,
    "Island Cave 1: Chest North-West After 1st Cultist": chest_locations_id_start + 99,
    "Island Cave 1: Chest East After 2st Cultist": chest_locations_id_start + 100,
    "Island Cave 1: Chest West After 2nd Cultist": chest_locations_id_start + 101,
    "Island Cave 1: Chest Near 3rd Cultist": chest_locations_id_start + 102,
    "Cold Harbour: Chest North-East of Waystone": chest_locations_id_start + 103,
    "Cold Harbour: Chest East of Iris": chest_locations_id_start + 104,
    "Frostville: Chest North of Waystone": chest_locations_id_start + 105,
    "Frostville: Chest South of Waystone": chest_locations_id_start + 106,
    "Frostville: Chest West of Town": chest_locations_id_start + 107,
    "Trail 15: Chest South of Frostville Entrence": chest_locations_id_start + 108,
    "Trail 15: Chest West of Mia": chest_locations_id_start + 109,
    "Trail 15: Chest South-West of Olga": chest_locations_id_start + 110,
    "Trail 16 Top: Chest South of Cave Entrence": chest_locations_id_start + 111,
    "Trail 16: Chest North of Karin": chest_locations_id_start + 112,
    "Trail 16: Chest North-West of Karin": chest_locations_id_start + 113,
    "Trail 16: Chest East of Dahlia": chest_locations_id_start + 114,
    "Abandoned Mine: Chest North of Trail 16 Entrence": chest_locations_id_start + 115,
    "Abandoned Mine: Chest South-West of House": chest_locations_id_start + 116,
    "Trail 17: Chest North of Clara": chest_locations_id_start + 117,
    "Trail 17: Chest South-East of Liv": chest_locations_id_start + 118,
    "Trail 17: Chest North-East of Karly": chest_locations_id_start + 119,
    "Trail 18: Chest South of Anabelle": chest_locations_id_start + 120,
    "Trail 18: Chest in North Part of Map": chest_locations_id_start + 121,
    "Trail 18: Chest North of Ingrid": chest_locations_id_start + 122,
    "Artic Temple: Chest in South-East": chest_locations_id_start + 123,
    "Artic Temple: Chest in West": chest_locations_id_start + 124,
    "Artic Temple: Chest in North-West": chest_locations_id_start + 125,

    "Trail 19: Chest Near Start": chest_locations_id_start + 126,
    "Trail 19: Chest South of 1st Crimson Cloak": chest_locations_id_start + 127,
    "Trail 19: Chest East of 2nd Crimson Cloak": chest_locations_id_start + 128,
    "Trail 20: Chest Near 1st Crimson Cloak": chest_locations_id_start + 129,
    "Trail 20: Chest Near 2nd Crimson Cloak": chest_locations_id_start + 130,
    "Trail 20 Right: Chest Near Cave Entrance": chest_locations_id_start + 131,
    "Trail 21: Chest Near Pushable Bolder": chest_locations_id_start + 132,
    "Trail 21: Chest North of Pond": chest_locations_id_start + 133,
    "Trail 21: Chest South area of map": chest_locations_id_start + 134,
    "Trail Spirit Passage: Chest north of first fork in path": chest_locations_id_start + 135,
    "Trail Spirit Passage: Chest in first loop area": chest_locations_id_start + 136,
    "Trail Spirit Passage: Chest north of first loop area": chest_locations_id_start + 137,
    "Trail Spirit Passage: Chest near 5th Crimson Cloak": chest_locations_id_start + 138,
    "Trail 22: Chest north west of pond": chest_locations_id_start + 139,
    "Trail 22: Chest north path before large grass patch": chest_locations_id_start + 140,
    "Trail 22: Chest north of large grass patch": chest_locations_id_start + 141,
    "Trail 22: Chest west side of lake near waypoint": chest_locations_id_start + 142,
    "Trail 22 Cave: Chest In Cave": chest_locations_id_start + 143,
}

warp_locations_id_start = chest_locations_id_start + 143
warp_locations = {
    "Oakwood Village WarpStone Activated": warp_locations_id_start+ 1,
    "Greensvale WarpStone Activated": warp_locations_id_start+ 2,
    "Trail 4 WarpStone Activated": warp_locations_id_start+ 3,
    "Dairy Farm WarpStone Activated": warp_locations_id_start+ 4,
    "Tumbleweed Town WarpStone Activated": warp_locations_id_start+ 5,
    "Crash Site WarpStone Activated": warp_locations_id_start+ 6,
    "Coconut Village WarpStone Activated": warp_locations_id_start+ 7,
    "Trail 14 WarpStone Activated": warp_locations_id_start+ 8,
    "Cold Harbor WarpStone Activated": warp_locations_id_start+ 9,
    "Frostville WarpStone Activated": warp_locations_id_start+ 10,
    "Abandoned Mine WarpStone Activated": warp_locations_id_start+ 11,
    "Trail 18 WarpStone Activated": warp_locations_id_start+ 12,
    "Trail 19 WarpStone Activated": warp_locations_id_start+ 13,
    "Trail 22 WarpStone Activated": warp_locations_id_start+ 14,
}

location_list = {
    **spirit_locations,
    **spirit_affection_locations,
    **Rare_spirit_locations,
    **main_quests,
    **side_quests,
    **battle_locations,
    **chest_locations,
    **warp_locations,
}
